//alert ('Acesta este JS site')

function f1(){
    alert('Acesta este un buton')
}

function f2(){
    alert('Aceasta este o imagine interactiva')
}

function pow2(){
    //document.getElementById('inp1').value
    //sa scriu in rezultat
    alert(document.getElementById('inp1').value*document.getElementById('inp1').value);
}

function pow3(){
  alert(document.getElementById('inp1').value*document.getElementById('inp1').value*document.getElementById('inp1').value)
}

function inm(){
  alert(document.getElementById('inp1').value*document.getElementById('inp2').value)
}

function imp() {
    alert(document.getElementById('inp1').value/document.getElementById('inp2').value)
}








































































































